### ISSUE TITLE
JSON stimulation sequence format

### ISSUE THREAD

**Issue by TheChymera** [IBT-FMI/COSplay#1]
If we decide to go with a high-level syntax, we really need to think about the issues/constraints it may cause in the long run.

Why do you feel there is a need to [specify the number of events explicitly](https://github.com/IBT-FMI/COSplay/blob/master/sequences.json#L3)?

**Comment by TheChymera** [comment]
In any case we need a further [parameter for the pulse duration](https://github.com/IBT-FMI/COSplay/blob/master/sequences.json#L8) (or maybe pulse_width is better to distinguish it from the duration of the event).

In out current standard optogenetic stimulation, for instance, we stimulate at 20Hz, but the pulse width is 5ms, meaning that the laser is on for 10% of the event duration, as opposed to 50%.

**Comment by TheChymera** [comment]
@faymanns  regarding the unit in our JSON format, I think it's best to express everything in seconds, and keep it TR-agnostic. Expressing times in TRs can be very confusing for TR different than 1s, and both expressing times in TR *or* ms is inconsistent with using Hz for the frequency.

**Comment by faymanns** [comment]
I change the time from ms to s. 5ba0bcaededa5cc36fda0e4bc1d47518298340f1

**Comment by TheChymera** [comment]
Could you please persistently track an example stimulation file with your code?

Also, I have been thinking about this, and since our current JSON format has the same subkeys for all keys, maybe a 2d datastructure would be more readable (and smaller in file size).

It may also help us attain better compatibility with [BIDS](http://bids.neuroimaging.io/bids_spec1.0.1.pdf) (one of the more modern and widely-used standards), as they recommend [a 2d structure  with columns similar to out keys](https://github.com/INCF/BIDS-examples/blob/master/ds101/sub-04/func/sub-04_task-Simontask_run-02_events.tsv) to track events during fMRI.

**Comment by faymanns** [comment]
Micropython doesn't have a csv module yet, but I can look into writing one. Alternatively, we could use json on the pyboard, but store tsv on the host. A major draw back of this approach would be, that you have to convert tsv to json if you want to do drag and drop.

**Comment by faymanns** [comment]
We agreed on using the BIDS format on both, the host and the pyboard.
