### ISSUE TITLE
Red LED

### ISSUE THREAD

**Issue by TheChymera** [IBT-FMI/COSplay#13]
t would be better to have an ther LED than the red one signal that the pyboard is in copy mode. The red one seems to be controlled depending on actually writing going on, and will be switched off after you have finished a write operation.

Additionally this allows users to diferentiate between the mode they are in (this would be the "other LED) and time periods where they have a very high chance of corrupting their memory if they unplug or reset (these would be the times when the red LED is on).
Ideally we would make a note of this "safety" feature as well.

**Comment by faymanns** [comment]
Changed copy mode LED to blue: 11aab718d5b10ffa96fa497ba447858612c00062
