### ISSUE TITLE
Capitalization

### ISSUE THREAD

**Issue by TheChymera** [IBT-FMI/COSplay#14]
Python, the programming language, is a proper noun, and thus capitalized. Same goes for MicroPython, which you can either write as MicroPython (capitalization preferred by the authors and respected by e.g. Wikipedia) or Micropython (treating it as a normal proper noun).

I spotted one in the README 9378d862d8c89669f7658856aa8eb0db411efe33 but it seems there are more occurences in the package,

**Comment by faymanns** [comment]
Fixed in be77f3481c13cfb5b36ee8b48080f9f234288075
