### ISSUE TITLE
Amplitude modulation for laser

### ISSUE THREAD

**Issue by TheChymera** [IBT-FMI/COSplay#15]
The amplitude modulation functionality provided by our stimulation file format, should be practically demonstrable with our Laser set-up.

Ideally you could call Omicron asap, and see if you need to make any changes with e.g. Markus Küpfer to implement the functionality in the device.

**Comment by faymanns** [comment]
I enabled the support for amplitude modulation in 603eb6fb35a31c8a1768237118734da78c3cb7c5.
