### ISSUE TITLE
Add overview entry for more LED codes

### ISSUE THREAD

**Issue by TheChymera** [IBT-FMI/COSplay#18]
However streamlined the workflow logic, new users will rely heavily on the LED patterns to indicate the status. It is particularly important to minimize confusion, by reducing the number of unexplained LED patterns. Two important patterns we do not currently list are:

- [ ] blue/red - for "writing to device"
- [ ] green/red - for "error encountered (e.g. sequence not recognised). Please Restart"

We should add them to the DOT file and printed overview.

**Comment by faymanns** [comment]
Blue and red is in the dot graph. Green/red is described in the text.
