### ISSUE TITLE
Amplitude-Modulated channels do not output enough voltage

### ISSUE THREAD

**Issue by TheChymera** [IBT-FMI/COSplay#19]
Apparently, channels 5 and 6 (which support amplitude modulation) are capped not at 3.3V (as channel 4 is) but at 1.2V. This means that they may be unusable to trigger devices with TTL inputs.

This issue can be somewhat mitigated by installing COSgen from the [`no_amplitude_modulation` branch](https://github.com/IBT-FMI/COSplay/tree/no_amplitude_modulation). However, under this solution, there are no longer any channels on the device supporting amplitude modulation (i.e. all output from 4,5,6 is 3.3V).

**Comment by faymanns** [comment]
Discussed on MicroPython forum:
https://forum.micropython.org/viewtopic.php?f=6&t=4101&p=23556#p23556

**Comment by faymanns** [comment]
I forked [micorpython](https://github.com/IBT-FMI/micropython) and pushed the changes I made to the source code.
