### ISSUE TITLE
Value Error: object not in sequence

### ISSUE THREAD

**Issue by felixsc1** [IBT-FMI/COSplay#22]
When starting COSplay the following error message appears:

```
Error on pyboard:
Traceback (most recent call last):
  File "main.py", line 323, in <module>
  File "main.py", line 197, in main
ValueError: object not in sequence
```

Before the error appears, it successfully connects to the pyboard and also detects the sequence on it.

**Comment by felixsc1** [comment]
seemed to be that the problem was with the sequence file, not with the software itself.

**Comment by TheChymera** [comment]
This issue can commonly be caused if the sequence contains a leading column of indexes.
