### ISSUE TITLE
Trigger threshold sensitivity

### ISSUE THREAD

**Issue by TheChymera** [IBT-FMI/COSplay#27]
The trigger module of one of our scanners is broken, and no longer triggers by going down from 3.5V to 0V but from 3.5V to 1.8V. Ofc the correct thing to do is to fix the hardware and not to break the software, but the former is taking a while.

In the mean time, is there any way to increase the sensitivity of the trigger?
As far as I understand [this](https://github.com/IBT-FMI/COSplay/blob/9a10c3f55b1f80c916d55acb3110402cdfda6fa5/pyboard/main.py#L180) is where the triggering happens, and the amplitude of the event is predefined by `pyb.ExtInt.IRQ_FALLING`, which is shipped with the micropython implementation. Any idea how this could be hacked? @faymanns @felixsc1

**Comment by faymanns** [comment]
Yes, that is right the line in your link sets the hardware interrupt for triggering. I am not sure you can change the voltage thresholds for this. 
It might be possible to try to use a resistor.
A resistor would lower both the 3.5V and the 1.8V, but maybe you can find a resistor of the right value, such that the high value is still above the threshold and the lower one below.

**Comment by TheChymera** [comment]
This was solved by repairing the hardware. Parameterizable sensitivity remains a nice-to-have, but in all fairness supporting broken hardware is no requirement for the project.
