### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by faymanns** [IBT-FMI/COSplay#3]
How should we handle timing error of the sequence? We could introduce a threshold (e.g. 1ms) for error handling. If the pyboard misses the deadline for the pulse by more than this the program stops. For smaller delays it only notifies the user and stores the error messages in an extra file which is stored in the same folder as the sequence on the host.

**Comment by TheChymera** [comment]
It is a considerably bigger nuisance for a user to have his stimulation interrupted than to get one missing pulse. This feature would be good for testing purposes, but should be relegated to optional once we are done. Ideally we would have a parameter `fatal_pulseskip` somewhere, which is `False` by default but can be switched to `True` by exigent users for which having a measurement with one missed pulse impedes their ability to analize the data more than having one entire experiment less in the data set.

**Comment by faymanns** [comment]
For now, I send a message to the program running on the host if a timing error occurs but I do not interrupt the stimulation. As the message is displayed instantly the user could interrupt the experiment manually. Furthermore the error messages are stored in a file called error.txt in the same directory as the sequence. Do you think I should implement the fatal_pulseskip parameter anyway?

**Comment by TheChymera** [comment]
If we decide to go for this, `fatal_pulseskip` is no longer needed. However, are you sure about this? Have we established that we can guarantee a connection between the pyboard and the scanner computer? If this connection is likely to be unavailable to a significant subset of users, we cannot rely on it, and we should provide a `fatal_pulseskip` functionality.

**Comment by faymanns** [comment]
I think it should work! If we use the pyboard in mass storage(& serial) mode the user should have permission to access the device. As far as modules go, we should be able to install pySerial in the user space using pip install --user pyserial.

**Comment by TheChymera** [comment]
ok, then there's no longer any need for a fatal skip parameter.
