### ISSUE TITLE
Package has no version

### ISSUE THREAD

**Issue by effigies** [IBT-FMI/COSplay#34]
```Shell
$ pip install .
Processing $DIR/COSplay
Building wheels for collected packages: COSplay
  Building wheel for COSplay (setup.py) ... done
  Stored in directory: /private/var/folders/yb/10x6vxlx40s1dhv5vc163m680000gp/T/pip-ephem-wheel-cache-17zpi6ha/wheels/8f/81/54/f726e6251e09278aca793f3475ff9d8af617261e2e93557dd6
Successfully built COSplay
Installing collected packages: COSplay
Successfully installed COSplay-0.0.0
```

A fairly simple option would be to use [Versioneer](https://github.com/warner/python-versioneer), which will use the latest git tag to produce a [PEP 440](https://www.python.org/dev/peps/pep-0440/)-compliant version string, avoiding the need for manual edits.

**Comment by TheChymera** [comment]
Seems trivial enough to not require a dedicated package. Does https://github.com/IBT-FMI/COSplay/commit/744db061b9ecf8ac39e8f58af47f80e0710c1b62 address the issue?

**Comment by effigies** [comment]
Sorry for the delay. Yes, that seems fine, it just means you have to manually update the version, which is easy to forget when tagging.

Also just a note that versioneer is a tool, not a dependency. It adds a couple files to your repo.

**Comment by TheChymera** [comment]
Thank you for the tool suggestion, but I would conclude this is solved as is now.
