### ISSUE TITLE
Example usage and automated tests missing

### ISSUE THREAD

**Issue by tanselbaran** [IBT-FMI/COSplay#38]
See JOSS review criteria and my comment [https://github.com/openjournals/joss-reviews/issues/1171#issuecomment-486387960](url) for details

**Comment by TheChymera** [comment]
Dear @tanselbaran , thank you for taking the time to review our project. Does the new [README section](https://github.com/IBT-FMI/COSplay#minimal-usage-example) address your open concerns?
