### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by TheChymera** [IBT-FMI/COSplay#4]
I see you have already added docstrings for many functions. That's great!

As elements of the API begin to harden, I suggest you also add parameters, returns and yields lists. The most widespread formatting guidelines in scientific python applications are those [provided by numpy](https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt). They are also compatible with [Sphinx](http://www.sphinx-doc.org/en/stable/). Though beautified documentation might be wasted on COSplay (but certainly not on COSgen).

**Comment by faymanns** [comment]
I'll take care of it once I have a version that works on the scanner computer.

**Comment by TheChymera** [comment]
I registered the repository with readthedocs. You can see the admin page [here](https://readthedocs.org/projects/cosplay/) and I can give you the according rights once you edit it.

Currently it's not building. I have not looked much into it, but by comparison the docs for LabbookDB [are building](http://labbookdb.readthedocs.io/en/latest/) (not that they're particularly extensive).

**Comment by faymanns** [comment]
My username is faymanns.
To build the docs you need the sphinx-argparse module. Can you give me access to the admin page? I think, I should be able to enable virtualenv there and add a requirements.txt. Hopefully that will solve the issue.
