### ISSUE TITLE
pkt.receive return None

### ISSUE THREAD

**Issue by skylin008** [IBT-FMI/COSplay#40]
Hi, I want to porting the pkt.py to pyboard.But when I run this code.It return None.How to solve this issue:
`from pkt import Packet

from pyb import UART

uart = UART(4, 9600)

pkt = Packet(uart)

test = "this is packet test"

while True:
    pkt.send(test.encode('utf8'))
    res = pkt.receive(time_out = 100)
    print(res)`

Thanks !

**Comment by faymanns** [comment]
I don't think we can help you unless you provide more details. It looks like you are trying to establish some kind of communication between the pyboard and a computer.
As this is not related to the COSplay code, I will close the issue. If I am wrong and your question is indeed related to our code, feel free to reopen the issue.
I suggested you have a look at Dave Hylands' [json-ipc repository](https://github.com/dhylands/json-ipc). It has examples that you might find helpful. In fact, most of the communication code in COSplay is based on code from that repository.

**Comment by skylin008** [comment]
Thank you faymanns，yes,I want to use this pkt protocol communication between pyboard and openmv board.
