### ISSUE TITLE
root access on scanner computer

### ISSUE THREAD

**Issue by faymanns** [IBT-FMI/COSplay#6]
I don't know for other vendors, but for Bruker scanners it seems like at least one person in every lab should have root access on the scanner computer(s). Because of this, I opt to stick with our original plan of using the USB virtual com port for communication between the microcontroller and the scanner computer.

**Comment by TheChymera** [comment]
Could you link to where you have gotten this information from? Have you been able to determine who in our lab has root access?

**Comment by faymanns** [comment]
Mark has root access and he gave me the password for 4T computer. He also said that most labs have some kind of system administrator, who takes care of these things and not the Bruker guys.

**Comment by TheChymera** [comment]
Ok. Good to know that this is possible. Ideally we would still handle as much automactically as possible, and keep the instructions for the system administrator as clear and short as possible. We wouldn't want to make the adoption contingent on whether or not the in-house administrator feels like doing a bit more work ;)

**Comment by faymanns** [comment]
How about a script that does what dirkt suggested on [superuser](https://superuser.com/questions/1195006/linux-connecting-to-a-usb-virtual-com-port-without-root-access)?

**Comment by TheChymera** [comment]
I see two possible reasons why a system admin would be disinclined to help with this:

* not willing to do the extra work
* not trusting/technically able enough to come to the conclusion that our script is not dangerous for the system.

To address both cases we could both write a script and ship it with COSplay, *and* write the single commands required for setting up permissions (along with a simple explanation for each) in a section of our README.

**Comment by faymanns** [comment]
Sounds good to me! I'll start writing the script;)
