### ISSUE TITLE
Terminal trigger feedback

### ISSUE THREAD

**Issue by TheChymera** [IBT-FMI/COSplay#8]
Things look to be working nicely. Ideally there would be some feedback which is written by the COSplay script to the terminal upon receiving the trigger.

**Comment by faymanns** [comment]
I decided not to do that because delays the earliest possible onset time. With out the feedback the first event can start ~76us after receiving the trigger. With the feedback it is ~330us.

**Comment by TheChymera** [comment]
Ok

**Comment by faymanns** [comment]
I added it anyway: 79eae44583477598360160a517f377b611978cad
