### ISSUE TITLE
Max sequence length in 'us'

### ISSUE THREAD

**Issue by faymanns** [IBT-FMI/COSplay#9]
Due to an overflow the 'us' accuracy mode only works for sequences with a max length of ~19min47s. (For the 'ms' mode it is ~317h, so not relevant.) As we originally only aimed for 'ms' accuracy, I suggest we mention it in the documentation but do not change anything.

**Comment by TheChymera** [comment]
It seemed to crash before the 19' mark, though. 10' alone would break it. Also my previous (phasic stimulation) sequences were working, in spite of being ~22' in length (from start of the sequence to the last pulse). 

Also, don't you think this issue may be better fixed? Seems like a small concern to limit the sub-ms accuracy mode over, now that it's implemented.

**Comment by faymanns** [comment]
I fixed this in 0428bdb9fc405a0b6c98c6376f5eaa85cc697595
